music_directory     "~/storage/shared/Music"
playlist_directory  "~/.config/mpd/playlists"
db_file             "~/.config/mpd/database"
pid_file            "~/.config/mpd/pid"
state_file          "~/.config/mpd/state"

bind_to_address     "0.0.0.0"
port                "6600"
restore_paused      "yes"

audio_output {
    type            "sles"
    name            "Android OpenSLES"
    mixer_type      "software"
}
